#!/usr/bin/env bash
# Ultroid - UserBot
# Copyright (C) 2021-2022 TeamUltroid
#
# This file is a part of < https://github.com/deadnote0009/Ultroidbot/ >
# PLease read the GNU Affero General Public License in <https://github.com/deadnote0009/Ultroidbot/blob/main/LICENSE/>.

if [ -d "resources" ]
then
    echo "Current directory Identified.."
else
    apt install git -y
    git clone https://github.com/deadnote0009/Ultroidbot/
    cd Ultroid
fi
bash resources/startup/termux.sh
